version: 1.0.0

service:
  bind:
    address: 0.0.0.0
    port: 8080
  shutdown_timeout: 5
  db_type: postgres # or memory

postgres:
  connection_string: postgres://root:rootpassword@postgres:5432/linksy
