openapi: 3.0.3
info:
  title: Linksy
  description: "URL Shortener"
  version: 1.0.0
servers:
  - url: /api

paths:
  /shorten:
    post:
      tags:
        - Shortener
      summary: Shorten given URL to a hash
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ShortenRequest"
        required: true
      responses:
        "500":
          description: Internal error
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShortenResponse"

  /retrieve:
    get:
      tags:
        - Shortener
      summary: Get original URL by hash
      security: []
      parameters:
        - $ref: "#/components/parameters/hashParam"
      responses:
        "500":
          description: Internal error
          content: {}
        "404":
          description: Not found in the database
        "409":
          description: Link is expired
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RetrieveResponse"

components:
  parameters:
    hashParam:
      in: query
      name: hash
      required: true
      schema:
        type: string

  schemas:
    ShortenRequest:
      $ref: "#/components/schemas/URL"

    ShortenResponse:
      type: object
      properties:
        hash:
          type: string

    RetrieveResponse:
      $ref: "#/components/schemas/URL"

    URL:
      type: object
      properties:
        url:
          type: string
          example: google.com
